server:
  port: 3002
spring:
  datasource:
    url: jdbc:postgresql://postgres-naruto.parchaa-hip:5432/naruto
    username: parchaa
    password: parchaa123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
