
server:
  port: 3004
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sakura
    username: parchaa
    password: parchaa123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
