spring:
  datasource:
    url: jdbc:postgresql://postgres-shizune:5001/shizune
    username: parchaa
    password: parchaa123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3003

application:
  config:
    naruto: http://NARUTO
