spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shizune
    username: parchaa
    password: parchaa123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3003

application:
  config:
    payment-url: naruto:3002
